// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdO6tryKQMjSCUMqKNo9WAKhAqCzDPfFM',
    appId: '1:504122404838:web:c466e465860a11dd493027',
    messagingSenderId: '504122404838',
    projectId: 'india-3e1bc',
    authDomain: 'india-3e1bc.firebaseapp.com',
    storageBucket: 'india-3e1bc.appspot.com',
    measurementId: 'G-Q7JP3Y3WXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnO0B5m5en8wtHeaJ7HzjUtu8AEhiKNqY',
    appId: '1:504122404838:android:706ca92f2b68d80a493027',
    messagingSenderId: '504122404838',
    projectId: 'india-3e1bc',
    storageBucket: 'india-3e1bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6FnzXCBJsN7JPWPdFEx7ZZosFeo2OToQ',
    appId: '1:504122404838:ios:2fd581684ac92e61493027',
    messagingSenderId: '504122404838',
    projectId: 'india-3e1bc',
    storageBucket: 'india-3e1bc.appspot.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6FnzXCBJsN7JPWPdFEx7ZZosFeo2OToQ',
    appId: '1:504122404838:ios:5873cfa5b49e856e493027',
    messagingSenderId: '504122404838',
    projectId: 'india-3e1bc',
    storageBucket: 'india-3e1bc.appspot.com',
    iosBundleId: 'com.example.demo.RunnerTests',
  );
}
